name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the app
        run: bun run release

      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: csc-${{ matrix.os == 'windows-latest' && 'exe' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
          path: build/csc
